[package]
name = "nau7802"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
enumflags2 = "0.7.10"
num_enum = "0.7.2"

[dev-dependencies]
embedded-hal-mock = { version = "0.11.0", features = ["eh1"] }
