M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Sun 29 Oct 2023 10:02:02 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T22:02:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.2Y-2.7
X6.2Y-3.6
X8.8Y-2.7
X8.8Y-3.6
T0
M30
