M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Wed 01 Nov 2023 09:21:17 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-01T09:21:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X4.2661Y-2.7768
X4.2661Y-2.885
T2
X5.4134Y-3.0551
X5.4134Y-3.4409
T0
M30
