M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu24.04.1} date 2025-01-11T18:55:09-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-11T18:55:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X4.3161Y-2.7768
X4.3161Y-2.885
T2
X5.6435Y-3.1043
X5.6435Y-3.4902
M30
