M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Sun 29 Oct 2023 10:01:32 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T22:01:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X4.3161Y-2.7768
X4.3161Y-2.885
T2
X5.4134Y-3.0551
X5.4134Y-3.4409
T0
M30
